### ISSUE TITLE
Bug: retrieving location

### ISSUE THREAD

**Issue by jmezna** [IoSL-INav/project#115]
If I share my location with beacon major/minor, then request my location, I get: 

``` json
{
"friends": [{
  "id": "359af8d6-449c-47fd-bdc4-0b5cb0a109eb",
  "name": "tub",
  "location": {
    "coordinates": [
      52.509851,
      13.32576
    ],
    "accuracyIndicator": 1
  }
}]
}
```

If I share lon, lat, building and floor, then request my location, I get:

``` json
{
"friends": [{
  "id": "359af8d6-449c-47fd-bdc4-0b5cb0a109eb",
  "name": "tub",
  "location": {
    "coordinates": [
      13.32611158490181,
      52.50973964499202
    ],
    "building": "mensa",
    "floor": "0",
    "accuracyIndicator": 2
  }
}]
}
```

Coordinates are not in same order in both requests.

**Comment by numbleroot** [comment]
Mhm, could it be the case that you retrieve the location on the device in the wrong order? Because the order is supposed to be [ longitude, latitude ] which seems fine for the beacon values (your first example). As in the backend code the order for saving a specific location is the same, it might be that you send `userLat` and `userLon` in the body of updateLocation in the wrong order. Could you please verify if you might have switched longitude and latitude?

**Comment by jmezna** [comment]
If it is supposed to be  [ longitude, latitude ], then pinpointing is working in right way. I think the problem are beacon coordinates from /hotspots. They are stored as  [latitude, longitude ] instead of  [ longitude, latitude ]. 

``` json
 {
"name": "shoe"
"companyUUID": "D0D3FA86-CA76-45EC-9BD9-6AF44C51822F"
"major": 9386
"minor": 56215
"location": {
"coordinates": [2]
0:  52.509646
1:  13.326402
-
"building": "Mensa"
"floor": "1st"
}
```

Right?

**Comment by boaerosuke** [comment]
Why are you by the way retrieving your OWN location from the server?

**Comment by jmezna** [comment]
Because I am my own friend. And I am retrieving friends location.
