### ISSUE TITLE
Bug setting email address in the federation provider, cleared after x time

### ISSUE THREAD

**Issue by hechi** [IoSL-INav/project#121]
jmezna discovered a bug at https://federation.cyclone-project.eu/auth/realms/master/account/ we have to add our email after sometime again, because its cleared out :disappointed: and then we cant use this email address again, so we have to register another one. I know this is only our workaround.

**Comment by mathiasslawik** [comment]
Ömer made some changes to the Federation Provider, which could have caused your federated user accounts getting other IDs as before. He'll delete all federated user accounts, so that it should work again.

I'm also in talk with TUB regarding the email adresses. We now know how we can get them, but I have to get clearance from the data protection officer.
